name: bit_markdown
description: "BitMarkdown is a minimal, fast, and Flutter-friendly Markdown and Latex renderer"
version: 0.0.5
homepage: https://github.com/BitCraftProduction/bit_markdown.git
repository: https://github.com/BitCraftProduction/bit_markdown.git

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_math_fork: ^0.7.4
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
